server:
  port: 8080
spring:
  application:
    name: isc-data-core
#  zipkin:
#    enabled: true
#    base-url: http://localhost:8081/  # zipkkin dashboard的地址：通过真实IP地址访问
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
#  sleuth:
#     sampler:
#       #  默认值为0.1f，现在为了测试设置100%采集
#       percentage: 1
    
    
    
#eureka:
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true

#日志配置
logging.level.root: warn
logging.level.com.lucksoft: warn